dist: trusty

language: node_js

os:
  - linux
  - osx

node_js:
  - 7

cache:
  directories:
    - node_modules
    - app/node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - xz-utils
      - icnsutils
      - graphicsmagick
      - rpm

install:
  - export CXX="g++-4.8"
  - npm install -g npm@latest
  - npm install

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then npm run package-mac    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run package-linux  ; fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/964abb64511d66538c2d
    on_success: change
    on_failure: always
    on_start: never
